### ISSUE TITLE
Feature requests for network programming

### ISSUE THREAD

**Issue by FedericoCeratto** [xomachine/NESM#1]
Thanks for the very useful library. NESM looks like the ideal candidate to create and parse network packets and implement protocols.
Would you consider supporting network/host endianness?
Also serialize() could call an optional Scapy-like helper that could set default and/or random values and fill in checksums before serialization. Thanks!

**Comment by xomachine** [comment]
Thank you for the feedback!
The endianness support is a good idea indeed. I will start working on it soon.
But could you clarify, support of what kind of helper you suggested? I have no experience with Scrapy (you mean the pythons web crawling framework, right?), so I would appreciate the detailed description of what should be passed as arguments to such a helper and what is expected as the result .

**Comment by FedericoCeratto** [comment]
@xomachine I was referring to http://www.secdev.org/projects/scapy/doc/usage.html
I'll PR a little demo of packet crafting.

**Comment by xomachine** [comment]
The endianness selection support is finally here. Along with the Stream interface ([documentation](https://xomachine.github.io/NESM/)).

Now about the helper procs.
I thought about ways to implement such a feature and have not found any. It's easy to write some random or default value fillers (E.g. [RandomStream](https://github.com/xomachine/NESM/blob/master/tests/helpers/rnw.nim#L17) from test helpers), but in more complicated cases like a checksum evaluation of the serialized part of structure I don't see how it can be implemented even on interface level. So any ideas are welcome.

**Comment by FedericoCeratto** [comment]
@xomachine supporting Enum fields would be useful for a lot of binary formats and protocols

**Comment by xomachine** [comment]
It will be hard to implement. I just don't know how to obtain the actual type of enum at the compile time.

**Comment by xomachine** [comment]
@FedericoCeratto Enum support have been introduced in the https://github.com/xomachine/NESM/commit/e5de913f836cd7499e07d9fb067aae3c1d0460bb commit of the devel branch. Not sure if this implementation is correct, but it can pass a simple unit test. Now I wonder if NESM should check enum data correctness (is the serialized value out of enum range or not).

**Comment by thompson4822** [comment]
I love NESM. It is absolutely awesome. I've recently run into an instance however where I need to deal with decoding/encoding C++ style bit fields like the following:

  AnExample* = object
    field2 {.bitsize:10.}: cuint
    field1 {.bitsize:8.}: cuint

Is there an easy way to do this in NESM? So far I'm not having much luck.

**Comment by xomachine** [comment]
@thompson4822 the closest thing to C++ bit field supported by NESM is **set[]**. But there is a problem with the custom size fields (only 1,2,4 bytes supported). I don't see any other ways to perform this for now, so I'll add this as a feature request to my TODO list for a future version.

But first, I want to know: what structure you are using to implement bitfield in Nim?

**Comment by thompson4822** [comment]
So right now, I believe that the pragma approach is just generating a uint32 behind the scenes. So, I could just model the data as that type for nesm and then manipulate it by casting it to a AnExample type first. Or ... maybe this is a job for a custom nesm converter. I'll give that a try!

**Comment by xomachine** [comment]
I've just realized, that the serialization of the C style bitfields is a REALLY bad idea. According to [this](https://stackoverflow.com/questions/15136426/memory-layout-of-struct-having-bitfields) stackoverflow answer, the bitfield memory layout is uncertain depends on compiler implementation. So it means that it is better to use **int** or **set**. The **set**s bits order is quite independent from underlying C compiler.

The bitsets as they are in C or C++ probably will never be implemented due to reasons above.

**Comment by thompson4822** [comment]
Dmitriy,
No problem. For me, I'm dealing with a bunch of structs that have bit
fields, but they are pretty much uniformly 32 bits in size. So in my Nim
type I can have this:

BitFields = object
  flag1 {.bitsize:8.}: cuint
  flag2 {.bitsize:12.}: cuint
  flag3 (.bitsize:8.}: cuint
  unused {.bitsize:4.}: cuint

Then for NESM, I can do this of course:

MyStruct = object
  id: uint64
  bitFields: uint32

and then in my code that needs to handle bitFields, I can just cast to/from
BitFields/uint32.

My use case by the way is that I have a very tightly packed database of
fixed length records (memory mapped). The structure of this data has
changed, and so now I need a quick and dirty ETL to map from the old format
to the new. Since I can't think of a language better suited to handling
this, I figure Nim + NESM is the perfect secret weapon :-)

Thanks for all your help and best regards as always,


Steve

**Comment by Riderfighter** [comment]
Wasn't sure if I should add onto this issue but here goes nothing.


Here are some enhancements that I feel would greatly improve the quality of life of those implementing certain protocols. It would be greatly beneficial if we were able to set the type used to prefix a string/seq natively without making a new type custom type. An example of how this could be implemented would be like this:
```nim
serializable:
  type
    CoolStrings* = object
      set: {endian: bigEndian, strLength: int16, seqLength:  int64}
      strings*: seq[string]
```
This would provide the user with a level of flexibility that is honestly so nice due to the simplicity of toggling said option.

Another feature which would be nice would be the ability to set the default value of a field, at least for me I'm re-implementing a certain games protocol and some packets might have additional bytes at the end which might get parsed into their respective variables. An example of this would be this:
```nim
serializable:
  type
    SpecialPacketWithFieldsThatMightExist* = object
      name*: string
      specialfield*: int32 as {default: 40}
```
This would give us the flexibility to give fields a default value other than 0 as is currently implemented in nim. This would allow us to parse packets which have the possibility of containing optional/additional data.

**Comment by xomachine** [comment]
Closing this issue to avoid messing many feature requests in one ticket
